### ISSUE TITLE
loading weight problem

### ISSUE THREAD

**Issue by vcvishal** [MrGiovanni/UNetPlusPlus#25]
Traceback (most recent call last):
  File "BRATS2013_application.py", line 287, in <module>
    activation=config.activation)
  File "D:\depressed\UNetPlusPlus-master\segmentation_models\xnet\model.py", line 86, in Xnet
    include_top=False)
  File "D:\depressed\UNetPlusPlus-master\segmentation_models\backbones\backbones.py", line 32, in get_backbone
    return backbones[name](*args, **kwargs)
  File "D:\depressed\UNetPlusPlus-master\segmentation_models\backbones\inception_v3.py", line 390, in InceptionV3
    model.load_weights(weights)
  File "D:\miniconda\lib\site-packages\keras\engine\network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "D:\miniconda\lib\site-packages\keras\engine\saving.py", line 1030, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 0 layers into a model with 188 layers.

please guide me 
thank you

**Comment by wpMelene** [comment]
Your weight file has 0 weights, which cannot be loaded into a model.
