### ISSUE TITLE
Deep supervision

### ISSUE THREAD

**Issue by twentyfiveYang** [MrGiovanni/UNetPlusPlus#29]
Hi @MrGiovanni ,thank you for sharing your code. 
I have a question about the implement of the Deep supervision structure. In the paper, you said that the final output of the model is the average of the 4 outputs of the branches. I calculate the average output feature map in this way but got the error below:`nestnet_output_1 = Conv2D(num_class, (1, 1), activation='sigmoid', name='output_1', kernel_initializer = 'he_normal', padding='same', kernel_regularizer=l2(1e-4))(conv1_2)
    nestnet_output_2 = Conv2D(num_class, (1, 1), activation='sigmoid', name='output_2', kernel_initializer = 'he_normal', padding='same', kernel_regularizer=l2(1e-4))(conv1_3)
    nestnet_output_3 = Conv2D(num_class, (1, 1), activation='sigmoid', name='output_3', kernel_initializer = 'he_normal', padding='same', kernel_regularizer=l2(1e-4))(conv1_4)
    nestnet_output_4 = Conv2D(num_class, (1, 1), activation='sigmoid', name='output_4', kernel_initializer = 'he_normal', padding='same', kernel_regularizer=l2(1e-4))(conv1_5)
    nestnet_output_all = (nestnet_output_1+nestnet_output_2+nestnet_output_3+nestnet_output_4)/4

    if deep_supervision:
        # model = Model(input=img_input, output=[nestnet_output_1,
        #                                        nestnet_output_2,
        #                                        nestnet_output_3,
        #                                        nestnet_output_4])
        model = Model(input=img_input, output=[nestnet_output_all])
    else:
        model = Model(input=img_input, output=[nestnet_output_4])
`

Using TensorFlow backend.
D:\code\unet-master\revisedModel.py:116: UserWarning: Update your `Model` call to the Keras 2 API: `Model(outputs=[<tf.Tenso..., inputs=Tensor("ma...)`
  model = Model(input=img_input, output=[nestnet_output_all])
Traceback (most recent call last):
  File "D:/code/unet-master/revisedModelTrain.py", line 16, in <module>
    model = Nest_Net(256,256,1)
  File "D:\code\unet-master\revisedModel.py", line 116, in Nest_Net
    model = Model(input=img_input, output=[nestnet_output_all])
  File "C:\Users\Administrator\Anaconda3\envs\tensorflow-gpu\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Administrator\Anaconda3\envs\tensorflow-gpu\lib\site-packages\keras\engine\network.py", line 93, in __init__
    self._init_graph_network(*args, **kwargs)
  File "C:\Users\Administrator\Anaconda3\envs\tensorflow-gpu\lib\site-packages\keras\engine\network.py", line 188, in _init_graph_network
    'Found: ' + str(x))
ValueError: Output tensors to a Model must be the output of a Keras `Layer` (thus holding past layer metadata). Found: Tensor("truediv:0", shape=(?, 256, 256, 1), dtype=float32)

Can you help about this, thanks!

**Comment by donghongwen** [comment]
Hello, I have the same problem as you. How did you solve it? @twentyfiveYang

**Comment by kevinkwshin** [comment]
Try this.

`    

    nestnet_output_all = keras.layers.Average()([nestnet_output_1,nestnet_output_2,nestnet_output_3,nestnet_output_4])

    if deep_supervision:
        model = Model(inputs=[img_input], outputs=[nestnet_output_all])

    else:
        model = Model(inputs=img_input, outputs=[nestnet_output_4])`

**Comment by zsk-tech** [comment]
In helper_functions.py :
     He writes as this:

if deep_supervision:
     model = Model(input=img_input, output=[nestnet_output_1,
                                            nestnet_output_2,
                                            nestnet_output_3,
                                            nestnet_output_4])

else:
    model = Model(input=img_input, output=[nestnet_output_4])

**Comment by Einshowstank** [comment]
I have the same question.

**Comment by MrGiovanni** [comment]
Hi @Einshowstank 

The deep supervision code is as below (you don't need to average outputs before computing loss):

```
% Architecture definition
def UNetPlusPlus(img_rows, img_cols, color_type=1, num_class=1, connection='concatenation', deep_supervision=False):

    ... ...

    nestnet_output_1 = Conv2D(num_class, (1, 1), activation='sigmoid', name='output_1', kernel_initializer = 'he_normal', padding='same', kernel_regularizer=l2(1e-4))(conv1_2)
    nestnet_output_2 = Conv2D(num_class, (1, 1), activation='sigmoid', name='output_2', kernel_initializer = 'he_normal', padding='same', kernel_regularizer=l2(1e-4))(conv1_3)
    nestnet_output_3 = Conv2D(num_class, (1, 1), activation='sigmoid', name='output_3', kernel_initializer = 'he_normal', padding='same', kernel_regularizer=l2(1e-4))(conv1_4)
    nestnet_output_4 = Conv2D(num_class, (1, 1), activation='sigmoid', name='output_4', kernel_initializer = 'he_normal', padding='same', kernel_regularizer=l2(1e-4))(conv1_5)

    if deep_supervision:
        model = Model(input=img_input, output=[nestnet_output_1,
                                               nestnet_output_2,
                                               nestnet_output_3,
                                               nestnet_output_4])
    else:
        model = Model(input=img_input, output=[nestnet_output_4])

    return model

% Model compiling
if config.deep_supervision:
    model.compile(optimizer=keras.optimizers.SGD(lr=config.lr, momentum=0.9, decay=0.0, nesterov=False), 
                  loss={'output_1': bce_dice_loss, 'output_2': bce_dice_loss, 'output_3': bce_dice_loss, 'output_4': bce_dice_loss},
                  metrics={'output_1': dice_coef, 'output_2': dice_coef,
                           'output_3': dice_coef, 'output_4': dice_coef},
                  loss_weights={'output_1': 1., 'output_2': 1., 'output_3': 1., 'output_4': 1.})
else:
    model.compile(optimizer=keras.optimizers.SGD(lr=config.lr, momentum=0.9, decay=0.0, nesterov=False), 
                  loss=bce_dice_loss, 
                  metrics=['binary_crossentropy', mean_iou, dice_coef])
```

Thanks,

Zongwei

**Comment by huazai2023** [comment]
@MrGiovanni How did you change the training sample?
Traceback (most recent call last):
  File "/data1/user/xiedehua/Model/Experiment/model_train_batch_v5.py", line 333, in <module>
    train(image_path, lable_path, train_percent, batch_size[i],
  File "/data1/user/xiedehua/Model/Experiment/model_train_batch_v5.py", line 254, in train
    history = model.fit(train_Generator, steps_per_epoch=len(train_dataset) // batch_size,
  File "/root/anaconda3/envs/TF/lib/python3.8/site-packages/keras/engine/training.py", line 1184, in fit
    tmp_logs = self.train_function(iterator)
  File "/root/anaconda3/envs/TF/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/root/anaconda3/envs/TF/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/root/anaconda3/envs/TF/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 759, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/root/anaconda3/envs/TF/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3066, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/root/anaconda3/envs/TF/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3463, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/root/anaconda3/envs/TF/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3298, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/root/anaconda3/envs/TF/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 1007, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/root/anaconda3/envs/TF/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 668, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/root/anaconda3/envs/TF/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 994, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /root/anaconda3/envs/TF/lib/python3.8/site-packages/keras/engine/training.py:853 train_function  *
        return step_function(self, iterator)
    /root/anaconda3/envs/TF/lib/python3.8/site-packages/keras/engine/training.py:842 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /root/anaconda3/envs/TF/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:1286 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /root/anaconda3/envs/TF/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2849 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /root/anaconda3/envs/TF/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:3632 _call_for_each_replica
        return fn(*args, **kwargs)
    /root/anaconda3/envs/TF/lib/python3.8/site-packages/keras/engine/training.py:835 run_step  **
        outputs = model.train_step(data)
    /root/anaconda3/envs/TF/lib/python3.8/site-packages/keras/engine/training.py:792 train_step
        self.compiled_metrics.update_state(y, y_pred, sample_weight)
    /root/anaconda3/envs/TF/lib/python3.8/site-packages/keras/engine/compile_utils.py:436 update_state
        self.build(y_pred, y_true)
    /root/anaconda3/envs/TF/lib/python3.8/site-packages/keras/engine/compile_utils.py:358 build
        self._metrics = tf.__internal__.nest.map_structure_up_to(y_pred, self._get_metric_objects,
    /root/anaconda3/envs/TF/lib/python3.8/site-packages/tensorflow/python/util/nest.py:1376 map_structure_up_to
        return map_structure_with_tuple_paths_up_to(
    /root/anaconda3/envs/TF/lib/python3.8/site-packages/tensorflow/python/util/nest.py:1458 map_structure_with_tuple_paths_up_to
        assert_shallow_structure(
    /root/anaconda3/envs/TF/lib/python3.8/site-packages/tensorflow/python/util/nest.py:1091 assert_shallow_structure
        raise ValueError(

    ValueError: The two structures don't have the same sequence length. Input structure has length 1, while shallow structure has length 4.
