### ISSUE TITLE
Implementing in colab

### ISSUE THREAD

**Issue by Swathi-Guptha** [MrGiovanni/UNetPlusPlus#52]
I have trying to run the following code in google colab.But, while importing the segmentation model i'm getting the following error:
Using TensorFlow backend.

---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

16 frames

ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     70 for some common reasons and solutions.  Include the entire stack trace
     71 above this error message when asking for help.""" % traceback.format_exc()
---> 72   raise ImportError(msg)
     73 
     74 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

Is there any update to the requirements file?

**Comment by maksym33** [comment]
Maybe try:
`%tensorflow_version 1.x`
from https://colab.research.google.com/notebooks/tensorflow_version.ipynb ?

**Comment by Swathi-Guptha** [comment]
1.! python -m pip install Keras==2.3.1 tensorflow==2.1.0 
2. import tensorflow.compat.v1 as tf
    tf.disable_v2_behavior() 
    print(tf.__version__)

After executing the requirements file we need to run the above two steps to run the code in colab

**Comment by deepaneez** [comment]
Unable to implement code in google colab even after following installation steps as mentioned. While importing segmentation models it says No module named 'segmentation_models'
from segmentation_models import Unet, Nestnet, Xnet
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-9364e51fdb83> in <module>()
----> 1 from segmentation_models import Unet, Nestnet, Xnet

ModuleNotFoundError: No module named 'segmentation_models'

**Comment by ItsCRC** [comment]
Epoch 1/70
74/74 [==============================] - 273s 4s/step - loss: 0.4780 - dice_coef: 0.5583 - val_loss: 5.9511 - val_dice_coef: 0.2558
NotImplementedError                       Traceback (most recent call last)
<ipython-input-28-0ab48d95d544> in <module>()
----> 1 history = model.fit(train_generator, validation_data=valid_generator, callbacks=callbackslist, epochs=70, verbose=1)
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/resource_variable_ops.py in numpy(self)
    582       return self.read_value().numpy()
    583     raise NotImplementedError(
--> 584         "numpy() is only available when eager execution is enabled.")
    585 
    586   @deprecated(None, "Prefer Dataset.range instead.")

NotImplementedError: numpy() is only available when eager execution is enabled.
